#!/usr/bin/env bash

#get name of the current directory
NAME=$(basename "$PWD")

#run the docker
docker run --name $NAME --network robomatic -p 5006:5006 -v /home/edgar/robomatic/github/robomatic-email-ms/resource:/home/resource -v /home/edgar/robomatic/github/evidence:/home/evidence $NAME
